# Generated by Django 5.2.13 on 2026-04-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='generation',
            field=models.IntegerField(default=0, help_text='Generation level (0 = oldest ancestors, higher numbers = descendants)'),
        ),
    ]
