# Generated by Django 5.2.13 on 2026-04-09 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0002_familymember_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Position within the generation; lower values appear first.'),
        ),
    ]
