# Generated by Django 5.2.13 on 2026-04-08 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_tree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipe_photos/')),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FAMILY', 'Family only'), ('SPECIFIC', 'Specific people')], default='FAMILY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_families', models.ManyToManyField(blank=True, related_name='shared_recipes', to='family_tree.familygroup')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='shared_recipes', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
